blank_issues_enabled: true
contact_links:
  - name: Emby Community Forum
    url: https://emby.media/community/
    about: Ask questions and discuss with the Emby community
  - name: Documentation
    url: https://github.com/Oratorian/emby-watchparty/blob/main/README.md
    about: Read the full documentation and setup guide
