name: Question / Discussion
description: Ask a question or start a discussion about Emby Watch Party
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question or want to discuss something? You're in the right place!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know or discuss?
      placeholder: "How do I..."
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic Area
      description: What is this question about?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - Troubleshooting
        - Development & Contributing
        - Security & Privacy
        - Performance & Optimization
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional information that might help answer your question
      placeholder: "I'm trying to set up... and I've already tried..."
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using (if applicable)?
      placeholder: "e.g., v1.0.4"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
