/* Generated by scripts/generate_socket_types.py. Do not edit. */
export interface ClientToServerPayloads {
  "auto_advance_cancel": {
    "party_id": string
  }
  "change_streams": {
    "party_id": string
    "audio_index"?: number | null
    "subtitle_index"?: number | null
    "quality"?: string | null
  }
  "chat_message": {
    "party_id": string
    "message": string
  }
  "heartbeat": {
    "party_id": string
    "time": number
  }
  "join_party": {
    "party_id": string
    "username"?: string
    "client_id"?: string
    "avatar_uuid"?: string | null
  }
  "join_vote": {
    "party_id": string
    "vote": "yes" | "no"
  }
  "leave_party": {
    "party_id": string
  }
  "pause": {
    "party_id": string
    "time": number
  }
  "play": {
    "party_id": string
    "time": number
  }
  "report_progress": {
    "party_id": string
    "time": number
  }
  "seek": {
    "party_id": string
    "time": number
    "was_playing"?: boolean
  }
  "select_video": {
    "party_id": string
    "item_id": string
    "item_name"?: string
    "item_overview"?: string
    "media_source_id"?: string | null
    "start_seconds"?: number
    "quality"?: string | null
  }
  "set_binge_watch_active": {
    "party_id": string
    "active": boolean
  }
  "stop_video": {
    "party_id": string
  }
  "stream_ready": {
    "party_id": string
  }
  "toggle_library": {
    "party_id": string
    "show": boolean
  }
  "update_avatar": {
    "party_id": string
    "avatar_uuid"?: string | null
  }
  "video_ended": {
    "party_id": string
  }
}
