/* Generated by scripts/generate_socket_types.py. Do not edit. */
export interface ClientToServerPayloads {
  "auto_advance_cancel": {
    "party_id": string
  }
  "change_streams": {
    "party_id": string
    "audio_index"?: number | null
    "subtitle_index"?: number | null
    "quality"?: string | null
  }
  "chat_message": {
    "party_id": string
    "message": string
  }
  "heartbeat": {
    "party_id": string
    "time": number
  }
  "join_party": {
    "party_id": string
    "username"?: string
    "client_id"?: string
    "avatar_uuid"?: string | null
  }
  "join_vote": {
    "party_id": string
    "vote": "yes" | "no"
  }
  "leave_party": {
    "party_id": string
  }
  "pause": {
    "party_id": string
    "time": number
  }
  "play": {
    "party_id": string
    "time": number
  }
  "report_progress": {
    "party_id": string
    "time": number
  }
  "seek": {
    "party_id": string
    "time": number
    "was_playing"?: boolean
  }
  "select_video": {
    "party_id": string
    "item_id": string
    "item_name"?: string
    "item_overview"?: string
    "media_source_id"?: string | null
    "start_seconds"?: number
    "quality"?: string | null
  }
  "set_binge_watch_active": {
    "party_id": string
    "active": boolean
  }
  "stop_video": {
    "party_id": string
  }
  "stream_ready": {
    "party_id": string
  }
  "toggle_library": {
    "party_id": string
    "show": boolean
  }
  "update_avatar": {
    "party_id": string
    "avatar_uuid"?: string | null
  }
  "video_ended": {
    "party_id": string
  }
}

export interface ServerToClientPayloads {
  "all_ready": {
    "time": number
    "username"?: string | null
    "playing"?: boolean | null
    "auto_binge"?: boolean | null
    "wait_for_ready"?: boolean | null
  }
  "auto_advance_cancelled": {
    "by_username"?: string | null
  }
  "auto_advance_fired": {
    "next_item_id": string
    "next_title": string
  }
  "auto_advance_pending": {
    "next_item_id": string
    "next_title": string
    "next_index_number"?: number | null
    "total_episodes": number
    "deadline": string
    "countdown_seconds": number
  }
  "binge_finished": {
    "reason"?: string | null
    "series_id"?: string | null
    "season_id"?: string | null
  }
  "binge_watch_state_changed": {
    "available": boolean
    "active": boolean
  }
  "chat_message": {
    "username": string
    "message": string
    "avatar_uuid"?: string | null
    "timestamp": string
  }
  "connected": {
    "sid": string
  }
  "drift_correction": {
    "time": number
    "username"?: string | null
    "playing"?: boolean | null
    "auto_binge"?: boolean | null
    "wait_for_ready"?: boolean | null
  }
  "error": {
    "message": string
  }
  "force_pause_before_seek": {
    "time": number
    "username"?: string | null
    "playing"?: boolean | null
    "auto_binge"?: boolean | null
    "wait_for_ready"?: boolean | null
  }
  "host_changed": {
    "host_username"?: string | null
    "host_client_id"?: string | null
    "is_admin"?: boolean
    "unlocked"?: boolean
    "reason"?: string | null
    "playing_only"?: boolean | null
    "previous_host"?: string | null
  }
  "host_left": {
    "host_username"?: string | null
    "host_client_id"?: string | null
    "is_admin"?: boolean
    "unlocked"?: boolean
    "reason"?: string | null
    "playing_only"?: boolean | null
    "previous_host"?: string | null
  }
  "host_reclaimed": {
    "host_username"?: string | null
    "host_client_id"?: string | null
    "is_admin"?: boolean
    "unlocked"?: boolean
    "reason"?: string | null
    "playing_only"?: boolean | null
    "previous_host"?: string | null
  }
  "join_rejected": {
    "message": string
    "retry_after"?: number | null
  }
  "join_vote_pending": {
    "timeout_seconds": number
    "eligible_voters": string[]
    "required_majority": number
  }
  "join_vote_resolved": {
    "result": "pass" | "fail" | "cancelled"
    "reason"?: string | null
  }
  "join_vote_started": {
    "username": string
    "timeout_seconds": number
    "eligible_voters": string[]
    "required_majority": number
  }
  "join_vote_update": {
    "votes": Record<string, "yes" | "no">
    "remaining": number
  }
  "members_update": {
    "users"?: string[]
    "members"?: ({ "username": string; "avatar_uuid"?: string | null })[]
    "username"?: string | null
    "rejoin"?: boolean | null
  }
  "party_dissolved": {
    "party_id": string
    "reason": string
  }
  "pause": {
    "time": number
    "username"?: string | null
    "playing"?: boolean | null
    "auto_binge"?: boolean | null
    "wait_for_ready"?: boolean | null
  }
  "play": {
    "time": number
    "username"?: string | null
    "playing"?: boolean | null
    "auto_binge"?: boolean | null
    "wait_for_ready"?: boolean | null
  }
  "ready_check_update": {
    "ready"?: string[]
    "waiting"?: string[]
  }
  "seek": {
    "time": number
    "username"?: string | null
    "playing"?: boolean | null
    "auto_binge"?: boolean | null
    "wait_for_ready"?: boolean | null
  }
  "streams_changed": {
    "video": { "item_id": string; "title": string; "overview"?: string; "stream_url"?: string | null; "audio_index"?: number | null; "subtitle_index"?: number | null; "media_source_id"?: string | null; "selected_by"?: string | null; "quality"?: string | null; "item_type"?: string | null; "series_id"?: string | null; "season_id"?: string | null; "episode_index"?: number | null; "episode_count"?: number | null; "next_item_id"?: string | null; "next_item_title"?: string | null; "run_time_seconds"?: number | null }
    "current_time": number
    "was_playing": boolean
  }
  "sync_state": {
    "current_video"?: { "item_id": string; "title": string; "overview"?: string; "stream_url"?: string | null; "audio_index"?: number | null; "subtitle_index"?: number | null; "media_source_id"?: string | null; "selected_by"?: string | null; "quality"?: string | null; "item_type"?: string | null; "series_id"?: string | null; "season_id"?: string | null; "episode_index"?: number | null; "episode_count"?: number | null; "next_item_id"?: string | null; "next_item_title"?: string | null; "run_time_seconds"?: number | null } | null
    "playback_state": { "playing": boolean; "time": number; "last_update": string }
    "users"?: string[]
    "binge_watch"?: { "available": boolean; "active": boolean } | null
    "pending_auto_advance"?: { "next_item_id"?: string | null; "next_title"?: string | null; "next_index_number"?: number | null; "total_episodes"?: number | null; "deadline"?: string | null; "countdown_seconds"?: number | null } | null
  }
  "toggle_library": {
    "show": boolean
  }
  "user_joined": {
    "users"?: string[]
    "members"?: ({ "username": string; "avatar_uuid"?: string | null })[]
    "username"?: string | null
    "rejoin"?: boolean | null
  }
  "user_left": {
    "users"?: string[]
    "members"?: ({ "username": string; "avatar_uuid"?: string | null })[]
    "username"?: string | null
    "rejoin"?: boolean | null
  }
  "video_ended": {
    "party_id": string
    "timestamp": string
  }
  "video_selected": {
    "video": { "item_id": string; "title": string; "overview"?: string; "stream_url"?: string | null; "audio_index"?: number | null; "subtitle_index"?: number | null; "media_source_id"?: string | null; "selected_by"?: string | null; "quality"?: string | null; "item_type"?: string | null; "series_id"?: string | null; "season_id"?: string | null; "episode_index"?: number | null; "episode_count"?: number | null; "next_item_id"?: string | null; "next_item_title"?: string | null; "run_time_seconds"?: number | null }
  }
  "video_stopped": {
    "message": string
    "stopped_by": string
  }
}
