"""
Utility Functions
Pure helpers for username generation and party code creation
"""

import secrets

ADJECTIVES = [
    "Happy",
    "Sleepy",
    "Brave",
    "Clever",
    "Swift",
    "Mighty",
    "Gentle",
    "Wise",
    "Lucky",
    "Bold",
    "Silent",
    "Wild",
    "Calm",
    "Fierce",
    "Noble",
    "Quick",
    "Bright",
    "Dark",
    "Golden",
    "Silver",
    "Ancient",
    "Young",
    "Mystic",
    "Cosmic",
    "Thunder",
    "Lightning",
    "Storm",
    "Frost",
    "Fire",
    "Shadow",
    "Crimson",
    "Azure",
    "Jade",
    "Ruby",
    "Diamond",
    "Steel",
    "Iron",
    "Crystal",
    "Blazing",
    "Frozen",
    "Electric",
    "Savage",
    "Loyal",
    "Royal",
    "Stellar",
    "Lunar",
    "Solar",
    "Astral",
    "Phantom",
    "Spirit",
    "Mighty",
    "Mega",
    "Super",
    "Ultra",
    "Hyper",
    "Quantum",
    "Cyber",
    "Ninja",
    "Samurai",
    "Warrior",
    "Epic",
    "Legendary",
    "Mythic",
    "Sacred",
    "Divine",
    "Radiant",
    "Glowing",
    "Shining",
    "Sparkling",
    "Dazzling",
]

NOUNS = [
    "Panda",
    "Tiger",
    "Eagle",
    "Dolphin",
    "Fox",
    "Wolf",
    "Bear",
    "Hawk",
    "Lion",
    "Owl",
    "Dragon",
    "Phoenix",
    "Falcon",
    "Raven",
    "Panther",
    "Jaguar",
    "Leopard",
    "Cheetah",
    "Lynx",
    "Cougar",
    "Shark",
    "Whale",
    "Orca",
    "Kraken",
    "Serpent",
    "Viper",
    "Cobra",
    "Python",
    "Anaconda",
    "Komodo",
    "Griffin",
    "Pegasus",
    "Unicorn",
    "Chimera",
    "Hydra",
    "Sphinx",
    "Minotaur",
    "Centaur",
    "Titan",
    "Golem",
    "Samurai",
    "Ninja",
    "Ronin",
    "Shogun",
    "Sensei",
    "Monk",
    "Knight",
    "Paladin",
    "Archer",
    "Ranger",
    "Wizard",
    "Sorcerer",
    "Mage",
    "Warlock",
    "Shaman",
    "Druid",
    "Sage",
    "Oracle",
    "Prophet",
    "Mystic",
    "Valkyrie",
    "Guardian",
    "Sentinel",
    "Watcher",
    "Protector",
    "Defender",
    "Champion",
    "Hero",
    "Legend",
    "Warrior",
    "Ghost",
    "Specter",
    "Wraith",
    "Phantom",
    "Spirit",
    "Shade",
    "Reaper",
    "Revenant",
    "Banshee",
    "Demon",
]


def generate_random_username() -> str:
    """Generate a random username like 'HappyPanda42'"""
    adjective = secrets.choice(ADJECTIVES)
    noun = secrets.choice(NOUNS)
    number = secrets.randbelow(99) + 1
    return f"{adjective}{noun}{number}"


def generate_party_code(existing_parties: dict) -> str:
    """
    Generate a unique 5-character alphanumeric party code.
    Excludes confusing characters (0, O, 1, I, L).
    """
    chars = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
    for _ in range(100):
        code = "".join(secrets.choice(chars) for _ in range(5))
        if code not in existing_parties:
            return code
    return secrets.token_urlsafe(8)
