from collections.abc import MutableMapping
from typing import Any, Awaitable, Callable

type Scope = MutableMapping[str, Any]
type Receive = Callable[[], Awaitable[MutableMapping[str, Any]]]
type Send = Callable[[MutableMapping[str, Any]], Awaitable[None]]

class AsyncServer:
    handlers: dict[str, dict[str, Callable[..., Awaitable[Any]]]]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def on(self, event: str, namespace: str | None = None) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    async def emit(self, event: str, data: Any = None, *args: Any, **kwargs: Any) -> Any: ...
    async def enter_room(self, sid: str, room: str, namespace: str | None = None) -> None: ...
    async def leave_room(self, sid: str, room: str, namespace: str | None = None) -> None: ...
    async def close_room(self, room: str, namespace: str | None = None) -> None: ...
    async def get_session(self, sid: str, namespace: str | None = None) -> dict[str, Any]: ...

class ASGIApp:
    def __init__(self, socketio_server: AsyncServer, *args: Any, **kwargs: Any) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
