"""Enforce coverage for executable lines added or changed by a patch."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

LineCoverage = dict[tuple[str, int], bool]


def _normalized(path: str) -> str:
    return path.replace("\\", "/").removeprefix("./")


def _changed_lines(diff: str) -> set[tuple[str, int]]:
    changed: set[tuple[str, int]] = set()
    path: str | None = None
    previous = ""
    for raw_line in diff.splitlines():
        # A real file header is always preceded by its `--- ` counterpart. An
        # ADDED line whose own content starts with "++ " also arrives here as
        # "+++ ...", and without this guard it was read as a header, silently
        # dropping the rest of that file's hunks.
        if raw_line.startswith("+++ ") and previous.startswith("--- "):
            candidate = raw_line[4:].split("\t", 1)[0]
            path = None if candidate == "/dev/null" else _normalized(candidate.removeprefix("b/"))
            previous = raw_line
            continue
        previous = raw_line
        if path is None or not raw_line.startswith("@@"):
            continue
        match = re.search(r"\+(\d+)(?:,(\d+))?", raw_line)
        if match is None:
            continue
        start = int(match.group(1))
        count = int(match.group(2) or "1")
        changed.update((path, line) for line in range(start, start + count))
    return changed


def _source_prefixes(root: ET.Element, repo_root: Path) -> list[str]:
    """Repo-relative roots that cobertura `filename` attributes hang off.

    coverage.py writes one <source> per --cov root and then reports every
    filename relative to whichever root contains it, so `backend/src/app.py`
    is emitted as `src/app.py`. Diff paths are repo-relative, so without this
    the two never intersect.
    """
    prefixes: list[str] = []
    for node in root.findall(".//sources/source"):
        text = (node.text or "").strip()
        if not text:
            continue
        try:
            relative = Path(text).resolve().relative_to(repo_root)
        except (ValueError, OSError):
            continue
        prefix = _normalized(str(relative))
        prefixes.append("" if prefix == "." else prefix)
    return prefixes


def _candidates(filename: str, prefixes: list[str], repo_root: Path) -> list[str]:
    if not prefixes:
        return [filename]
    joined = [_normalized(f"{prefix}/{filename}") if prefix else filename for prefix in prefixes]
    # The report names a file relative to exactly one root; picking the root
    # that actually holds it keeps two same-named modules under different
    # roots from being credited with each other's coverage.
    existing = [candidate for candidate in joined if (repo_root / candidate).exists()]
    if existing:
        return existing
    # Report produced elsewhere, or the file has since moved. Keeping every
    # candidate over-matches, which is far better than measuring nothing.
    return [*joined, filename]


def _cobertura(path: Path, repo_root: Path) -> LineCoverage:
    coverage: LineCoverage = {}
    # Reports are generated by this workflow, never accepted from users.
    root = ET.parse(path).getroot()  # noqa: S314
    prefixes = _source_prefixes(root, repo_root)
    for class_node in root.findall(".//class"):
        filename = _normalized(class_node.attrib["filename"])
        for name in _candidates(filename, prefixes, repo_root):
            for line_node in class_node.findall("./lines/line"):
                key = (name, int(line_node.attrib["number"]))
                coverage[key] = coverage.get(key, False) or int(line_node.attrib["hits"]) > 0
    return coverage


def _lcov(path: Path, prefix: str) -> LineCoverage:
    coverage: LineCoverage = {}
    filename: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if raw_line.startswith("SF:"):
            source = _normalized(raw_line[3:])
            filename = _normalized(f"{prefix}/{source}" if prefix else source)
        elif filename is not None and raw_line.startswith("DA:"):
            number, hits, *_ = raw_line[3:].split(",")
            key = (filename, int(number))
            coverage[key] = coverage.get(key, False) or int(hits) > 0
    return coverage


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    diff_source = parser.add_mutually_exclusive_group(required=True)
    diff_source.add_argument("--base", help="Git base revision used for BASE...HEAD")
    diff_source.add_argument("--diff-file", type=Path, help="Read unified diff from this file")
    parser.add_argument("--python-report", type=Path, required=True)
    parser.add_argument("--frontend-report", type=Path, required=True)
    parser.add_argument("--frontend-prefix", default="frontend")
    parser.add_argument("--threshold", type=float, default=80.0)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Root the diff paths are relative to; cobertura sources are re-based onto it",
    )
    return parser


def _measured(executable: set[tuple[str, int]], suffixes: tuple[str, ...]) -> int:
    return sum(1 for filename, _ in executable if filename.endswith(suffixes))


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.diff_file:
        diff = args.diff_file.read_text(encoding="utf-8")
    else:
        git = shutil.which("git")
        if git is None:
            raise RuntimeError("git is required to compute changed-line coverage")
        # Fixed argv, no shell; base remains one revision argument.
        diff = subprocess.run(  # noqa: S603
            [git, "diff", "--unified=0", f"{args.base}...HEAD", "--"],
            check=True,
            capture_output=True,
            encoding="utf-8",
        ).stdout

    repo_root = args.repo_root.resolve()
    coverage = _cobertura(args.python_report, repo_root)
    coverage.update(_lcov(args.frontend_report, args.frontend_prefix))
    changed = _changed_lines(diff)
    executable = changed & coverage.keys()
    covered = sum(coverage[line] for line in executable)
    total = len(executable)
    percent = 100.0 if total == 0 else covered / total * 100

    print(
        f"Changed-line coverage: {covered}/{total} ({percent:.2f}%); "
        f"required: {args.threshold:.2f}%"
    )
    # Printed unconditionally. This gate previously matched zero Python lines
    # and still reported 100%, so a per-language breakdown is what makes that
    # class of failure visible instead of silently green.
    for label, suffixes in (("python", (".py",)), ("frontend", (".ts", ".vue", ".js"))):
        touched = _measured(changed, suffixes)
        measured = _measured(executable, suffixes)
        note = (
            "  <- changed but none measured, check report paths" if touched and not measured else ""
        )
        print(f"  {label}: {measured} executable of {touched} changed line(s){note}")
    uncovered = sorted(line for line in executable if not coverage[line])
    if uncovered:
        print("Uncovered changed lines:")
        for filename, number in uncovered:
            print(f"  {filename}:{number}")
    return int(percent < args.threshold)


if __name__ == "__main__":
    raise SystemExit(main())
