"""Enforce coverage for executable lines added or changed by a patch."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

LineCoverage = dict[tuple[str, int], bool]


def _normalized(path: str) -> str:
    return path.replace("\\", "/").removeprefix("./")


def _changed_lines(diff: str) -> set[tuple[str, int]]:
    changed: set[tuple[str, int]] = set()
    path: str | None = None
    for raw_line in diff.splitlines():
        if raw_line.startswith("+++ "):
            candidate = raw_line[4:].split("\t", 1)[0]
            path = None if candidate == "/dev/null" else _normalized(candidate.removeprefix("b/"))
            continue
        if path is None or not raw_line.startswith("@@"):
            continue
        match = re.search(r"\+(\d+)(?:,(\d+))?", raw_line)
        if match is None:
            continue
        start = int(match.group(1))
        count = int(match.group(2) or "1")
        changed.update((path, line) for line in range(start, start + count))
    return changed


def _cobertura(path: Path) -> LineCoverage:
    coverage: LineCoverage = {}
    # Reports are generated by this workflow, never accepted from users.
    root = ET.parse(path).getroot()  # noqa: S314
    for class_node in root.findall(".//class"):
        filename = _normalized(class_node.attrib["filename"])
        for line_node in class_node.findall("./lines/line"):
            key = (filename, int(line_node.attrib["number"]))
            coverage[key] = coverage.get(key, False) or int(line_node.attrib["hits"]) > 0
    return coverage


def _lcov(path: Path, prefix: str) -> LineCoverage:
    coverage: LineCoverage = {}
    filename: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if raw_line.startswith("SF:"):
            source = _normalized(raw_line[3:])
            filename = _normalized(f"{prefix}/{source}" if prefix else source)
        elif filename is not None and raw_line.startswith("DA:"):
            number, hits, *_ = raw_line[3:].split(",")
            key = (filename, int(number))
            coverage[key] = coverage.get(key, False) or int(hits) > 0
    return coverage


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    diff_source = parser.add_mutually_exclusive_group(required=True)
    diff_source.add_argument("--base", help="Git base revision used for BASE...HEAD")
    diff_source.add_argument("--diff-file", type=Path, help="Read unified diff from this file")
    parser.add_argument("--python-report", type=Path, required=True)
    parser.add_argument("--frontend-report", type=Path, required=True)
    parser.add_argument("--frontend-prefix", default="frontend")
    parser.add_argument("--threshold", type=float, default=80.0)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.diff_file:
        diff = args.diff_file.read_text(encoding="utf-8")
    else:
        git = shutil.which("git")
        if git is None:
            raise RuntimeError("git is required to compute changed-line coverage")
        # Fixed argv, no shell; base remains one revision argument.
        diff = subprocess.run(  # noqa: S603
            [git, "diff", "--unified=0", f"{args.base}...HEAD", "--"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout

    coverage = _cobertura(args.python_report)
    coverage.update(_lcov(args.frontend_report, args.frontend_prefix))
    executable = _changed_lines(diff) & coverage.keys()
    covered = sum(coverage[line] for line in executable)
    total = len(executable)
    percent = 100.0 if total == 0 else covered / total * 100

    print(
        f"Changed-line coverage: {covered}/{total} ({percent:.2f}%); "
        f"required: {args.threshold:.2f}%"
    )
    uncovered = sorted(line for line in executable if not coverage[line])
    if uncovered:
        print("Uncovered changed lines:")
        for filename, number in uncovered:
            print(f"  {filename}:{number}")
    return int(percent < args.threshold)


if __name__ == "__main__":
    raise SystemExit(main())
