"""Generate committed TypeScript REST types from FastAPI OpenAPI."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from fastapi import FastAPI

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.src.routers import (  # noqa: E402
    admin,
    auth,
    avatar,
    health,
    library,
    media,
    party,
    quality,
)


def _type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if reference:
        return reference.rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(dict.fromkeys(_type(item) for item in schema["anyOf"]))
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = _type(schema.get("items", {}))
        return f"({item})[]" if " | " in item else f"{item}[]"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            fields = [
                f"{json.dumps(name)}{'' if name in required else '?'}: {_type(value)}"
                for name, value in properties.items()
            ]
            return "{ " + "; ".join(fields) + " }"
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_type(additional)}>"
        return "Record<string, unknown>"
    return "unknown"


def render() -> str:
    application = FastAPI()
    for router in (admin, auth, avatar, health, library, media, party, quality):
        application.include_router(router.router)
    schemas = application.openapi().get("components", {}).get("schemas", {})
    lines = ["/* Generated by scripts/generate_openapi_types.py. Do not edit. */", ""]
    for name, schema in sorted(schemas.items()):
        lines.append(f"export type {name} = {_type(schema)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "frontend" / "src" / "types" / "api.generated.ts"
    expected = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            print("Generated REST contract is stale: frontend/src/types/api.generated.ts")
            return 1
        return 0
    path.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
