"""Generate committed Socket.IO JSON Schema and TypeScript payload types."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.src.socket_protocol import INBOUND_MODELS, OUTBOUND_MODELS  # noqa: E402


def _typescript_type(schema: dict[str, Any], root: dict[str, Any]) -> str:
    if "$ref" in schema:
        prefix = "#/$defs/"
        reference = schema["$ref"]
        if reference.startswith(prefix):
            definition = root.get("$defs", {}).get(reference[len(prefix):], {})
            return _typescript_type(definition, root)
    if "anyOf" in schema:
        values = [_typescript_type(value, root) for value in schema["anyOf"]]
        return " | ".join(dict.fromkeys(values))
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item_type = _typescript_type(schema.get("items", {}), root)
        if " | " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if kind == "object":
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            fields = []
            for name, value in properties.items():
                optional = "" if name in required else "?"
                fields.append(
                    f"{json.dumps(name)}{optional}: {_typescript_type(value, root)}"
                )
            return "{ " + "; ".join(fields) + " }"
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_typescript_type(additional, root)}>"
        return "Record<string, unknown>"
    return "unknown"


def _render_interface(name: str, schemas: dict[str, dict[str, Any]]) -> list[str]:
    lines = [f"export interface {name} {{"]
    for event, schema in schemas.items():
        required = set(schema.get("required", []))
        if not schema.get("properties"):
            lines.append(f"  {json.dumps(event)}: Record<string, never>")
            continue
        lines.append(f"  {json.dumps(event)}: {{")
        for field_name, field_schema in schema.get("properties", {}).items():
            optional = "" if field_name in required else "?"
            lines.append(
                f"    {json.dumps(field_name)}{optional}: {_typescript_type(field_schema, schema)}"
            )
        lines.append("  }")
    lines.extend(["}", ""])
    return lines


def render() -> tuple[str, str]:
    inbound_schemas = {
        event: model.model_json_schema(mode="validation")
        for event, model in sorted(INBOUND_MODELS.items())
    }
    outbound_schemas = {
        event: model.model_json_schema(mode="serialization")
        for event, model in sorted(OUTBOUND_MODELS.items())
    }
    schema_text = json.dumps(
        {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "client_to_server": inbound_schemas,
            "server_to_client": outbound_schemas,
        },
        indent=2,
        sort_keys=True,
    ) + "\n"

    lines = ["/* Generated by scripts/generate_socket_types.py. Do not edit. */"]
    lines.extend(_render_interface("ClientToServerPayloads", inbound_schemas))
    lines.extend(_render_interface("ServerToClientPayloads", outbound_schemas))
    return schema_text, "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema_text, types_text = render()
    output_root = args.output_dir or ROOT
    schema_path = output_root / "backend" / "socket-events.schema.json"
    types_path = output_root / "frontend" / "src" / "types" / "socket.generated.ts"

    if args.check:
        stale = []
        for path, expected in ((schema_path, schema_text), (types_path, types_text)):
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(output_root)))
        if stale:
            print("Generated socket contracts are stale: " + ", ".join(stale))
            return 1
        return 0

    schema_path.parent.mkdir(parents=True, exist_ok=True)
    types_path.parent.mkdir(parents=True, exist_ok=True)
    schema_path.write_text(schema_text, encoding="utf-8", newline="\n")
    types_path.write_text(types_text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
